/** @format */

export const workExps = [
  {
    id: 0,
    company: "Amazon",
    title: "Software Developer Engineer Intern",
    location: "Toronto, ON",
    description: [
      "Developed, tested, and deployed full-stack, internationalized features (22 countries) whilst leveraging Java, React (Typescript, Javascript, Redux, Jest) for the Advertising Console product within the Amazon Ads org",
      "Devised technical strategies by diagnosing architectural software approaches while collaborating closely with key stakeholders, estimating effort & work for features, and executing task planning to exactitude",
      "Constructed a QuickSight dashboard for business intelligence analysis & improved operational excellence for internal UI library by approximately 75%",
    ],
    startDate: "June 2022",
    endDate: "Aug 2022",
  },
  {
    id: 1,
    company: "IBM",
    title: "Software Developer Intern",
    location: "Toronto, ON",
    description: [
      "Drove the development of transitioning a Legacy Web Application to a Single Page Application for the IBM Business Process Manager (BPM) software in a Scrum environment",
      "Developed RESTful APIs through the OpenAPI Specification and refactored Java EE backend logic, as well as worked on the database layer (DB2)",
      "Refactored and developed reliable frontend pages in React with Typescript and CSS from JSP, Dojo, GWT pages written in Java",
      "Implemented i18n (internationalization) as well as IBM standardized accessibility requirements within the SPA",
      "Utilized Jira, Git, Jenkins, JFrog Artifactory and IBM RTC to organize tasks through functional needs and manage CI/CD pipelines",
      "Investigated and produced fixes for defects and bugs within the IBM Business Process Manager software",
    ],
    startDate: "May 2021",
    endDate: "June 2022",
  },
  {
    id: 2,
    company: "Toronto Metropolitan University",
    title: "Research Assistant",
    location: "Toronto, ON",
    description: [
      "Spearheading the development of efficient ML models for in-game emotion recognition for therapeutic VR games",
      "Explored and implemented custom ML (CNN) model deployment onto Unity3D with C# on several OS (Android, etc.)",
      "Collaborating with the director of multimedia at TMU, post-doctorate student, several undergraduate RAs",
    ],
    startDate: "May 2023",
    endDate: "Present",
  },
  {
    id: 3,
    company: "Innovation Boost Zone - Aetava",
    title: "Frontend Developer",
    location: "Toronto, ON",
    description: [
      "Developed and integrated a custom-made mood board plugin for a WordPress application",
      "Implemented a React + Canvas app using Javascript & HTML/CSS, utilizing the WooCommerce API",
    ],
    startDate: "May 2023",
    endDate: "Present",
  },
  {
    id: 4,
    company: "Helium Aero",
    title: "Android Application Developer",
    location: "Toronto, ON",
    description: [
      "Developed an Android application (Java) that interfaces with drones from scratch based off of Figma prototype",
      "Utilized Java & XML to build Android application along with a Mavlink Java library to communicate between drone",
      "Employed UDP communication between simulated drone and Android devices to send and receive Mavlink packets",
    ],
    startDate: "Mar 2021",
    endDate: "Jul 2021",
  },
  {
    id: 5,
    company: "Lightening Group LLC.",
    title: "Frontend Developer",
    location: "Remote",
    description: [
      "Developed a frontend using React paired with the Next.js framework, Typescript, Tailwind CSS to format components, as well as GraphQL to communicate with the backend",
      "Worked with a client geared toward launching a pharmaceutical web application, and collaborated with a team of developers through Git",
      "Utilized Cypress to conduct E2E testing to ensure bugs weren’t present in codebase as well as ensure seamless delivery",
    ],
    startDate: "Sep 2020",
    endDate: "Dec 2020",
  },
  {
    id: 6,
    company: "Toronto Metropolitan University",
    title: "Undergraduate Research Assistant",
    location: "Toronto, ON",
    description: [
      "Researched and compared different MQTT Mosquitto Clustering implementations based on latency and design aspects",
      "Analysed 1000+ lines of code written in C to document structure and components of clusters",
      "Conducted localized broker testing & assisted with configuration & deployment of MQTT Clusters into the cloud",
    ],
    startDate: "Jun 2020",
    endDate: "Aug 2020",
  },
  {
    id: 7,
    company: "Balancever",
    title: "Android Developer",
    location: "Toronto, ON",
    description: [
      "Spearheaded a Full-stack Android (Java, XML, Gradle) application from scratch in an Agile environment; utilizing Git to coordinate with other developers",
      "Instituted backend with Firebase Auth (3rd Party OAuth2) & Realtime Database; integrating several APIs (ie. GCP)",
      "Constructed several algorithms to create a custom android calendar and sort events",
    ],
    startDate: "May 2020",
    endDate: "Aug 2020",
  },
];

export const projects = [
  {
    id: 0,
    title: "SmartFridgeAddOn",
    short_description: "IoT Embedded device + Machine Learning + Web App",
    description:
      "My Computer Engineering undergraduate capstone project (spanning over two semesters). Our objective was to design an add-on package for existing fridges through an easy to install hardware rig coupled with an intelligent cloud-based analysis software that could turn any fridge into a 'smart' one.",
    image: `images/SFAO.png`,
    tags: [
      "Python",
      "PyTorch",
      "YOLOv7",
      "Roboflow",
      "Flask",
      "Luxonis SDK",
      "Bash scripts",
      "Raspbian",
      "Raspberry Pi Zero 2 W",
      "Oak-D-Lite",
      "Google Colab",
      "React",
      "CSS",
      "Firebase Auth",
      "Firebase Cloudstore DB",
      "Jira",
    ],
    code: "https://github.com/DeluxeViper/SmartFridgeAddOn",
    demo: "",
  },
  {
    id: 1,
    title: "SmoothieMakersClub",
    short_description: "Full Stack Web Application",
    description:
      "A Progressive Web Application that brings all Smoothie Makers alike to come together, create healthy & nutritious recipes, and share them with each other.",
    image: `images/SmoothieWebsite.png`,
    tags: [
      "Java",
      "Python",
      "Spring Boot",
      "MySQL",
      "Javascript",
      "CSS",
      "HTML",
      "Spring Data JPA",
      "AWS Elastic Beanstalk",
      "AWS RDS",
      "BeautifulSoup4",
      "Selenium",
      "Vaadin",
      "OAuth2.0",
    ],
    code: "https://github.com/DeluxeViper/SmoothieWebsite",
    demo: "",
  },
  {
    id: 2,
    title: "MemoryGo",
    short_description: "Cross-Platform Mobile Application",
    description:
      "MemoryGo is a flashcard tool that lets you study without realization while you play games, surf the internet, watch a video, chat with friends or any other task.",
    image: `images/MemoryGo.png`,
    tags: ["Dart", "Java (Android)", "XML", "SQL (SQLite)", "Gradle"],
    code: "https://github.com/DeluxeViper/Memorygo",
    demo: "https://play.google.com/store/apps/details?id=com.ceruleansource.MemoryGo",
  },
  {
    id: 3,
    title: "Cooking Recipe Suggestion Web App",
    short_description: "Full Stack Web Application",
    description:
      "With 1930 ingredients and 1489 recipes, Cook.io is a web application that provides cooking recipes to users based on the ingredients they input.",
    image: `images/CRS-Web-App.png`,
    tags: [
      "Javascript",
      "Express.",
      "React",
      "MaterialUI",
      "Python",
      "Redis (caching)",
      "Firebase Auth",
      "Firebase Cloud Firestore",
      "Jira",
      "Figma",
    ],
    code: "https://github.com/DeluxeViper/Cooking-Recipe-Suggestion-Web-App",
    demo: "",
  },
  {
    id: 4,
    title: "Livestream App",
    short_description: "Android Mobile Application",
    description:
      "A mobile app that allows the user to either broadcast their own stream and/or find and join streams happening around them through a google maps populated with a series of markers that indicate the myriad of logged in users that might or might not be streaming.",
    image: `images/livestream.jpeg`,
    tags: ["Kotlin", "XML", "Room", "Retrofit", "OkHttp3", "Dagger", "GCP"],
    code: "https://github.com/DeluxeViper/LivestreamApp",
    demo: "",
  },
  {
    id: 5,
    title: "Livestream Backend",
    short_description: "RESTful API Backend",
    description:
      "A backend for a livestreaming client application that consumes it. This backend's capabilities ranges from JWT user authentication, to being able to manage the MongoDB database that it's connected to.",
    image: `images/server.jpeg`,
    tags: [
      "Java",
      "Spring (Boot, Security, Web, Reactive MongoDB)",
      "MongoDB",
      "JWT",
      "NGINX",
      "RTMP",
      "Docker (Compose)",
    ],
    code: "https://github.com/DeluxeViper/livestreambackend-mongodb",
    demo: "",
  },
  {
    id: 6,
    title: "Torrent Clone",
    short_description: "P2P CLI application",
    description:
      "A P2P application (created in C) that allows peers to share and download content through an index server via UDP and TCP communication. (Complete technical description on github)",
    image: `images/p2p_image.jpeg`,
    tags: ["C", "UDP", "TCP", "GCC", "Makefile"],
    code: "https://github.com/DeluxeViper/TorrentClone",
    demo: "",
  },
  {
    id: 7,
    title: "Air Traffic Control System",
    short_description: "Distributed System - CLI Application",
    description:
      "Collaborated with a team of 4 individuals to create an Air Traffic Control System that uses technologies such as RabbitMQ and gRPC to ensure a distributed, scalable, secure and robust system inspired by the AeroMACS communication system (with some modifications).",
    image: `images/ATS.jpg`,
    tags: ["Python", "RabbitMQ", "gRPC", "Docker compose"],
    code: "https://github.com/nigel5/air-traffic-control-system",
    demo: "",
  },
];

export const TimeLineData = [
  {
    year: 2018,
    month: "Sept",
    text: "Started Computer Engineering (B. Eng) at Toronto Metropolitan University",
  },
  {
    year: 2021,
    month: "May",
    text: "Started IBM SWE internship",
  },
  {
    year: 2022,
    month: "May",
    text: "Ended IBM SWE internship",
  },
  {
    year: 2023,
    month: "Aug",
    text: "Completed Amazon internship",
  },
  {
    year: 2023,
    month: "May",
    text: "Graduated with a Computer Engineering (B. Eng) degree from Toronto Metropolitan University",
  },
];
